- src/aics-image-viewer/assets/styles/axis-style-override.css
- src/aics-image-viewer/components/AxisClipSliders/index.tsx
- src/aics-image-viewer/components/AxisClipSliders/styles.css
- src/aics-image-viewer/components/BottomPanel/index.tsx
- src/aics-image-viewer/components/CellViewerCanvasWrapper/index.jsx
Resolves #48 by restyling the ROI sliders and associated elements to [specification](https://xd.adobe.com/view/904d6444-a800-48b6-8844-4f6f116d85ab-c51e). Highlights include: color coded axis sliders, new slider handles that allow dragging ranges even when the range is very small, restyled play buttons with tooltips.
Also: sliders step along integer values, numeric readouts should update more reliably when slider is moved with arrow keys, and the `BottomPanel` component gets a `title` prop.
NOTE: some color choices, particularly in play buttons, are chosen specifically to stand out against the dark backdrop of CFE and don't work well at all with the current default look of web-3d-viewer. A separate PR in the very near future will attempt to consolidate some styles from CFE, clean up …
> Feature/ROI sliders: styling

- public/index.jsx
loading images via urls of the form:
/?dataset=aics_hipsc_v2021.1&id=587902
was broken.
This is a simple update to restore that functionality.
> update to be able to load cell ids from CFE datasets

- src/aics-image-viewer/components/AxisClipSliders/index.tsx
- src/aics-image-viewer/components/AxisClipSliders/styles.css
Finishes resolving #49 by making axis sliders have only one handle in 2D modes.
Given that slider state is stored internally as `[number, number]`, this is accomplished like this:
1. in the `Nouislider` component, if we're in 2d mode, pass only the first number from state as a handle position, not both
2. in event handlers, if we get only a single-element array of values back, treat this element as both the start and end of the slice and store that value in both state fields
Screenshot:
> Feature/ROI sliders: single-slice in 2d mode

- src/aics-image-viewer/components/AxisClipSliders/index.tsx
- src/aics-image-viewer/components/AxisClipSliders/styles.css
Resolves #50 by replacing the sliders with an error message at very narrow widths, and allowing play buttons to shift to below the slice numbers to make more room for the slider in 2d mode.
NOTE: the `@media` query at the bottom of AxisClipSliders/styles.css was accidentally included as part of the last pull request, but was added as part of this task. See [this commit](https://github.com/allen-cell-animated/website-3d-cell-viewer/pull/64/commits/cb70a78852a75d872aa43f6bf82b453d418214bc) for those changes.
Screenshots:
> Feature/ROI sliders: responsive design

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/Toolbar/index.tsx
Resolves #74: adds a screenshot button to the location [specified](https://xd.adobe.com/view/904d6444-a800-48b6-8844-4f6f116d85ab-c51e/screen/a01f264e-ec99-42ab-a84a-90f2e17a533b/specs/). When the user clicks it, the viewer will download a screenshot of the current view named "screenshot.png."
Screenshot:
> Feature: screenshot button

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
- src/aics-image-viewer/shared/constants.ts
- src/aics-image-viewer/shared/utils/viewerChannelSettings.ts
`App` currently has two required props named `maskChannelName`, one on the base `AppProps` type and one on `ViewerChannelSettings`. Neither actually affect anything because the segmentation channel name is hardcoded via the constant `CELL_SEGMENTATION_CHANNEL_NAME`.
- Remove the prop on `AppProps`, make the one on `maskChannelName` optional.
- Remove `CELL_SEGMENTATION_CHANNEL_NAME` and make the viewer search for the channel named by the prop instead. I have confirmed this still works in CFE, because it already sets this prop to the same value as was previously hardcoded.
> Fix/remove duplicate `maskChannelName`

- public/index.tsx
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
The first revision of zarr loading was assuming that the first level under the .zarr store was a collection of images.  But really, usually there is just a single .zarr image.
This is a quick update to handle that so we can look at some data from the Brain science institute. The whole arrangement of url handling and dealing with multi-image, multi-resolution and multi-time is still a bit TBD for a future ticket.
Full loading also depends on https://github.com/allen-cell-animated/volume-viewer/pull/71 and there will be a small version bump once that pr is merged.
> handle zarr urls when there is no sub-image

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
The `transform` prop on `App` has fields `translate` and `rotate`, but transforms in the Variance dataset, for which the prop was originally added, has fields `translation` and `rotation`. Passing transforms directly in from CFE doesn't work.
Change the names.
Note that this is a breaking change: any dependent software that has come to rely on this interface in the hour since v2.4.0 was published will unfortunately need to be updated.
> transform fields: `translate`/`rotate` -> `translation`/`rotation`

- package-lock.json
- package.json
- src/aics-image-viewer/components/App/ChannelUpdater.tsx
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/AxisClipSliders/styles.css
- src/aics-image-viewer/components/CellViewerCanvasWrapper/index.tsx
- src/aics-image-viewer/shared/constants.ts
Update volume-viewer to 3.2.0 and use its new APIs and features.
Since the last version, the API for volume loaders has changed, `View3d` gained a method for changing time in a time series, and a new time step indicator has been added.
- Update image loading to use the new `IVolumeLoader` API; stores created loaders in a ref for use when loading time series images
- Use the new `setTime` method to move through time (using the stored loader) without creating a new `Volume`
- Use the new time step indicator; add logic to move scale bars out of its way when present
- Remove the current image's `LoadSpec` as an element of state, since `Volume` objects now store their own `LoadSpec`s
- Vertically centers the clipping sliders (unrelated to the update, but it was a bit of the design I missed)
- …
> Feature/viewer 3.2.0

- public/index.tsx
- src/aics-image-viewer/components/App/index.tsx
Most CFE datasets use a `baseUrl` and then combine it with a `cellPath` which is the individual image name. 
The use of `subpath` was doubling up the filename and causing bad urls when fetching zarr data.  `subpath` is really supposed to be used for multiresolution level and not much else. (A future change will have to address this naming)
This changeset just stops putting any information in subpath, and adjusts the standalone app inputs accordingly.  
This should fully enable CFE datasets to support zarr as the file format for 3d viewer!
> fix zarr loading from CFE

- public/index.tsx
Trying to load a tiff url from AWS was failing due to a trailing slash added to the file path.  This fixes it.  The slash will only be added if it is needed to separate `url` and `image`.  If `image` is not provided, then `url` will be assumed to be the whole path.
This change is only for the standalone static web app and does not change the React component.
Repro:
https://allen-cell-animated.github.io/website-3d-cell-viewer/?url=https://animatedcell-test-data.s3.us-west-2.amazonaws.com/HAMILTONIAN_TERM_FOV_VSAHJUP_0000_000192.ome.tif
> fix bug with trailing slash when url points to complete file (tiff)

- public/index.tsx
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
- src/aics-image-viewer/components/AxisClipSliders/index.tsx
- src/aics-image-viewer/components/CellViewerCanvasWrapper/index.tsx
Added a url parameter to set camera mode at initialization of the standalone viewer. 
In doing so, there is one behavior change: camera views will now remember their clipping slider settings, even when loading new images.
We also discovered something out of sync between the axis clipping sliders and the initial view state, so we changed the way the slider state is held by the app.  
Pair programmed with @frasercl
> Camera mode in url params

- src/aics-image-viewer/components/MetadataViewer/styles.css
Fixing #176 
Seems to work to just add display:none to the collapsed css.
Could use help testing/verifying on Chrome/Firefox/Safari
> fix info panel accordion collapse on Safari

- src/aics-image-viewer/components/App/ChannelUpdater.tsx
Quick fix: currently, channel settings are not updated on channels that are never loaded. When allen-cell-animated/volume-viewer#173 is published, disabled channels may never be loaded when the user moves to a new time point. Currently, this would cause these channels to be stuck in the disabled state. This change allows the enabled/disabled setting to be changed on unloaded channels.
> Allow unloaded channels to be enabled

- package-lock.json
- package.json
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/shared/constants.ts
The latest version of volume-viewer introduces the `VolumeLoaderContext`, which can offload volume loaders to a WebWorker where they won't block rendering and updates. This PR updates volume-viewer and replaces the current single-threaded loader creation with creation mediated by `VolumeLoaderContext`.
> Use workerized loading

- package-lock.json
- package.json
- src/aics-image-viewer/components/App/index.tsx
volume-viewer added a concept of "prefetch priority" (#181) which enables forcing the zarr loader to prioritize a given axis or set of axes when prefetching. This feature was designed for playback in this viewer: when playing through time in z-slice mode, we should not be issuing prefetch requests for adjacent z slices, e.g. Update volume-viewer and connect axis playing state to prefetch priority.
> Prioritize prefetching playing axis

- src/aics-image-viewer/components/App/index.tsx
Currently, the transfer function is automatically updated every time new data is loaded into the volume. Scientists would prefer if it remained constant between time steps and z slices.
Track when data is being loaded into the `Volume` for the first time, and only regenerate the transfer function on that load.
> Don't update transfer function on reloads

- .github/workflows/aws-deploy.yml
Mismatched role name between github actions and AWS
successful run: https://github.com/allen-cell-animated/website-3d-cell-viewer/actions/runs/8530408054/job/23368194654
> mismatched role name

- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/shared/utils/controlPointsToLut.ts
This change picks up a change from volume-viewer to let control points be out of range, so they are remembered when they have to be remapped multiple consecutive times.  We adopt volume-viewer's method for rebuilding the lookup table array from the control points. 
Bonus bug fix: control points receiving a color change but no position change, were not actually updating colors in the view.  Added an update call to make sure it happens.
(volume viewer PR linked below)
> Fix control point remapping

- public/firebase/index.ts
- public/index.tsx
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
Review time: pretty quick (~20min)
Closes allen-cell-animated/volume-viewer#78: allow users to take advantage of volume-viewer's new ability to load zarrs from multiple data sources.
Like the props they replace, `imageUrl` and `parentImageUrl` specify the paths from which to load image data. They correspond to the old `cellPath` and `fovPath` props, respectively, in that they specify what CFE calls "single cell" and "full field" images. However, they are different from the old set of data-loading props in the following ways:
- With `baseUrl` gone, **both URLs must be fully qualified**. No more automatically picking two files out of a single parent directory.
- **Both props may be `string[]`.** When passed down to volume-viewer to get a loader, a `string[]` will create a (zarr) loader …
> Allow multiple data sources for zarr volumes

- public/App.css
- public/index.html
- public/index.tsx
- src/aics-image-viewer/assets/styles/globals.css
- src/aics-image-viewer/assets/styles/typography.css
- src/aics-image-viewer/assets/styles/variables.css
- src/aics-image-viewer/components/StyleProvider/index.tsx
- src/aics-image-viewer/components/StyleProvider/styles.css
- src/aics-image-viewer/styles/ant-vars.less
- src/landing-page/components/LandingPage/content.ts
- src/landing-page/components/LandingPage/index.tsx
Implements styling of the landing page, Pt. II of #188. I expect to maybe have 1-2 more PRs before this issue is fully closed.
*Estimated size: medium, 20 minutes.*
Changes:
- Adds the banner video MP4, which autoplays when loaded.
- Also added an accessibility feature, where the video playback is disabled if `prefers-reduced-motion` is set to true.
- Adds `Open Sans` via Google fonts. Existing fonts are still included to ensure compatibility with embedded use cases, but will be removed in the future.
- Adds the `StyleProvider` component, which will wrap the `LandingPage` and `App` in the future to provide a central location for CSS variables.
- Implements styling for the landing page.
| Design | Implementation |
| --- | --- | 
| …
> feature: Landing page styling

- src/aics-image-viewer/components/ControlPanel/index.tsx
- src/aics-image-viewer/components/StyleProvider/index.tsx
- src/aics-image-viewer/components/Toolbar/index.tsx
- website/components/AppWrapper.tsx
- website/components/Buttons/index.tsx
- website/components/HelpDropdown.tsx
- website/components/LandingPage/index.tsx
Closes #220, implementing the help menu in the top header bar.
*Estimated size: small-medium, 20 minutes*
- Edits CSS variables to reflect the primary/secondary/tertiary styling defined in the the original UX Figma file.
- Adds a `SecondaryButton` styled component. (purple outline that goes to full highlight color when hovered)
- Adds outline to the modals and dropdowns and adjusts content styling.
- Adds the `getContainer` or `getPopupContainer` to all the places we are using dropdowns to ensure styling is applied.
- Adds the `HelpDropdown` component, containing a menu of buttons and links.
**Video walkthrough (🔊):**
https://github.com/allen-cell-animated/website-3d-cell-viewer/assets/30200665/40809ec8-a282-493b-8c04-ab0933d130e3
> feature: Help menu implementation

- package.json
Closes #250.
- Add a trailing slash to the basenames.
> fix: Fix GH Pages missing build files

- website/components/ErrorPage.tsx
Fixes an issue where the error page content was slightly off-center and caused a horizontal scrollbar to appear.
*Estimated review size: tiny, 1 minute*
> fix: Bad padding on error page

- website/components/LandingPage/content.tsx
Fixes a bug where the starting density made it impossible to actually see the cells. 
*Estimated review size: tiny, 1 minute*
Before:
After:
> fix: Decreased example nucmorph dataset density

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/ChannelsWidget.tsx
- src/aics-image-viewer/components/ViewerStateProvider/index.tsx
- src/aics-image-viewer/components/ViewerStateProvider/types.ts
Review time: small (10-15min)
Currently, if we try to update multiple viewer or channel settings synchronously, only the last update will be applied:
```typescript
changeViewerSetting("maskAlpha", 0.5); // overwritten by next update
changeViewerSetting("autorotate", true); // only this update is applied
```
This is due to the fact that setters like `changeViewerSetting` produce a new value for `viewerSettings` by pulling and updating the current value in state. But since that state value only gets updated on every render, multiple synchronous updates will end up pulling and modifying the same stale state value. So e.g. above, the first call produces a new value for `viewerSettings` by copying the current value and updating `maskAlpha`, then the second call pulls the same value from …
> Use reducers for viewer state

- src/aics-image-viewer/components/shared/SmarterSlider.tsx
Review time: tiny <1min (+ a few minutes for this longish description)
Resolves #280: time slider can get into "stuck" condition: after the user has interacted with the slider manually, it no longer updates while playing through time series.
This was caused by a dumb mistake I made while converting the `SmarterSlider` component to a function component.
`SmarterSlider` is a very thin wrapper around the `Nouislider` React component, which is itself a smallish wrapper around the nouislider library. `SmarterSlider` adds a `React.memo` around `Nouislider` to skip rendering under certain conditions, but `Nouislider` [already has a `memo`](https://github.com/mmarkelov/react-nouislider/blob/d567861674ac2ab76a78d307c09932a5aeb99433/src/index.js#L273). What's going on?
One of the changes that can …
> fix `SmarterSlider` memo function

- src/aics-image-viewer/components/StyleProvider/index.tsx
- website/components/LandingPage/index.tsx
Problem
=======
Closes #288 , fixing visual hierarchy + layout on landing page.
*Estimated review size: tiny, 5-10 minutes*
Solution
========
- Adjusts spacing on datasets to group titles and paragraph text.
- Adjusts font size on project titles.
- Fixes "In review" label alignment
- Fixes gaps between feature callout titles and text.
Screenshots
=======
Before:
After:
> fix: 3DVV landing page layout

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/shared/utils/controlPointsToLut.ts
- src/aics-image-viewer/shared/utils/viewerChannelSettings.ts
- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Closes #282, saving the control points to the URL!
*Estimated review size: large, 30 minutes*
This change adds the following properties to the URL:
```
controlPoints - 'cps'
controlPointsEnabled - 'cpe'
ramp - 'rmp'
```
(^ I'm open to feedback on any of these abbreviations)
These capture the current control point and ramp information, as well as whether the control points OR ramp should be visible 
in the UI (now shown under the 'Advanced' checkbox in the volume settings editor).
Note that `rmp` is slightly redundant with the existing `lut` field in the URL; I elected to keep them separate as we expect `lut` to be a user input property, while the `ramp` and `controlPoints` are only used when capturing existing state from the user interacting with the viewer.
- Adds `controlPoints`, …
> feat: Save control point info to URL

- package-lock.json
- package.json
- src/aics-image-viewer/shared/utils/controlPointsToLut.ts
Review time: tiny (<5min)
#294 introduced the need to remap a set of control points manually, independent of volume-viewer's normal update cycle. Currently, this is accomplished by creating an instance of volume-viewer's `Lut` object and remapping it. This is both unnecessarily verbose and inefficient, since this causes the `Lut` to automatically create a `Uint8Array` and fill it in multiple times with lookup table values that will never be used.
allen-cell-animated/volume-viewer#227 exported the underlying function which `Lut` uses to remap control points. This PR picks up that change.
> Use control point remap function

- package-lock.json
- package.json
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
- src/aics-image-viewer/components/ViewerStateProvider/index.tsx
- src/aics-image-viewer/components/ViewerStateProvider/types.ts
- website/components/AppWrapper.tsx
- website/components/Modals/ShareModal.tsx
- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Closes #283, saving the camera position + rotation to the URL.
**Estimated review size: small, 15 minutes*
- Updates `url_utils` to support saving and parsing the camera's position, rotation, target position, and up vector to and from the URL.
- Hoists the `view3d` as a ref up to the top-level `AppWrapper`, so that the current camera transform information can be accessed as soon as the user hits the "Share URL" modal.
- We do this because saving the current camera transform to the `ViewerState` would cause a state update every time we change the camera transform. This is really expensive, and there isn't a simple way to listen for changes to begin with, so it's best to only query the camera transform when we need it.
For a camera with the following properties:
```
position: [0, 0, 5] …
```
> feat: Store and load camera info from the URL

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/ChannelsWidget.tsx
- src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
- src/aics-image-viewer/components/ViewerStateProvider/index.tsx
- src/aics-image-viewer/shared/constants.ts
- website/components/Modals/ShareModal.tsx
- website/utils/datatype_utils.ts
- website/utils/test/datatype_utils.test.ts
- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Closes #302, decreasing URL length.
*Estimated review size: large, 30-40 minutes*
(Many of the changes are unit tests.)
Before:
> https://volumeviewer.allencell.org/viewer?url=https%253A%252F%252Fallencell.s3.amazonaws.com%252Faics%252Fnuc_morph_data%252Fdata_for_analysis%252Fbaseline_colonies%252F20200323_06_mid%252Fraw.ome.zarr%2Chttps%253A%252F%252Fallencell.s3.amazonaws.com%252Faics%252Fnuc_morph_data%252Fdata_for_analysis%252Fbaseline_colonies%252F20200323_06_mid%252Fseg.ome.zarr&mode=volumetric&mask=0&image=cell&axes=0&bb=0&bbcol=ffffff&bgcol=000000&rot=0&bright=70&dens=2.5&interp=1&reg=0%3A1%2C0%3A1%2C0%3A1&slice=0.5%2C0.5%2C0.5&lvl=35%2C140%2C255&t=0&view=Z&c0=ven%3A1%2Csen%3A0%2Cisv%3A128%2Cisa%3A1%2Cclz%3A0%2Ccza%3A1%2Ccol%3Ac3c3c3%2Ccps%3A-26.64179104477612%253A0%253Affffff%252C …
> fix: Shorten URLs

- src/aics-image-viewer/shared/constants.ts
- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Closes #310, where unspecified camera parameters in URLs would cause the "XZ" view mode to fail.
*Estimated review size: small, 5 minutes*
The underlying cause was that the default viewer settings were being used, which specify the position `(0, 0, 5)` by default for 3D viewing. In the orthographic Y-slice view mode, however, this led to the camera being at position 0 in the Y axis. This meant that the camera would be "inside" the desired slice, and show only a black screen.
- Changes the default viewer state's camera state to be `undefined`. If the camera settings are not specified in the URL, the camera state will be set to `undefined`, which signals the viewer not to edit the camera's position/rotation/etc.
- Added a separate `getDefaultCameraState`, which returns the default camera …
> fix: Fix bug where unspecified camera in URL would cause black screen in Y slice mode.

- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Missed float formatting/URL shortening for two parameters, the region and slice! 
This change adds formatting to both and a unit test to validate the result.
*Estimated review size: tiny, 5 minutes*
> fix: Shorten ramp and slice parameters

- public/App.css
- src/aics-image-viewer/components/StyleProvider/index.tsx
- website/components/LandingPage/index.tsx
Completes the cookie settings section of #317, "Prepare for allencell: thumbnail, short description, [Cookie Settings] anchor link".
*Estimated size: small, 5 minutes*
These changes are almost entirely copied from TFE, which uses the same cookie banner.
- Adds the cookie banner anchor link and associated styling.
- Adds style overrides for the cookie banner, copied from TFE https://github.com/allen-cell-animated/timelapse-colorizer/blob/main/src/styles/cookie-banner.css
Popup banner:
New Cookie settings link:
Styled menu:
> feat: Styled cookie banner, added link to cookie settings

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/nightly.yml
- .github/workflows/pr-preview.yml
Closes #241 ("Add PR previews via GitHub pages") and #218 "Update the PR template".
Much of these changes was copied from TFE, where we're already using the PR preview system.
*Estimated review size: small, 5-10 minutes*
- Updates the PR template format to match other repos.
- Adds the PR preview action so PRs will automatically have a GitHub pages preview build associated with them.
- Updates the existing nightly build to prevent overwriting of PR previews.
- PR preview! https://allen-cell-animated.github.io/website-3d-cell-viewer/pr-preview/pr-326/
> feat: Updated PR format, added PR previews

- src/aics-image-viewer/shared/utils/controlPointsToLut.ts
Default LUT had 3 control points and our code was not handling it well.
In production viewer, this url would load and ultimately reset its luts to a generic fullrange LUT which made the image invisible.
With the changes, the volumes show up as expected.
https://allen-genetic-tools.s3.amazonaws.com/tissuecyte/1298553550/ome-zarr
The code change is just trying to make a reasonable guess at a min/max from the given LUT control points.
> Fix invisible brain image

- src/aics-image-viewer/shared/utils/viewerState.ts
Problem
=======
Closes #325, "don't rename channels in `ChannelState`."
*Estimated review size: tiny, 2 minutes*
Solution
========
- `initializeOneChannelSetting` no longer renames channels unless no value is provided.
* Bug fix (non-breaking change which fixes an issue)
> fix: Channels are no longer renamed

- src/aics-image-viewer/assets/styles/noui-slider-override.css
- src/aics-image-viewer/components/AxisClipSliders/index.tsx
Problem
=======
Closes #303, "last timepoint is (N-1)/N".
Subtracted 1 from the max to reflect zero-based indexing used for time and z-index.
*Estimated review size: tiny, <5 minutes*
Solution
========
- Timepoint denominator now matches maximum slider value.
- Sorted imports.
- Copied a change from #324 which fixes a rendering bug in the slider.
* Bug fix (non-breaking change which fixes an issue)
Screenshots (optional):
-----------------------
> fix: Slider max now reflects zero-based indexing

- README.md
- public/gh-reroute/404.html
- public/index.html
- website/components/Header.tsx
- website/components/LandingPage/index.tsx
Problem
=======
Part of #331, renaming. Renames the app to "Vol-E" in the header, HTML documents, landing page content, and README.
*Estimated review size: tiny, <5 minutes*
Solution
========
- Renames "Volume Viewer" to "Vol-E".
- Adjusts some grammar for consistency (oxford commas, etc.)
Screenshots (optional):
-----------------------
Interactive preview here: https://allen-cell-animated.github.io/website-3d-cell-viewer/pr-preview/pr-335/
> refactor: Updated name from Volume Viewer to Vol-E on landing page

- src/aics-image-viewer/components/StyleProvider/index.tsx
- website/components/LandingPage/index.tsx
Problem
=======
Closes #339, "Update tag styling on homepage so it doesn't hurt user's eyes".
*Estimated review size: tiny, <5 minutes*
Solution
========
- Updates styling on "In Review" flag to a border and grey text.
Screenshots (optional):
-----------------------
Before:
After:
> fix: Changed "In Review" flag styling

- src/aics-image-viewer/components/App/index.tsx
Problem
=======
Fixes #342, "Volumes that are initially disabled are remapped incorrectly when enabled."
The issue seemed to be caused by the `initialLoadRef` only allowing normal initialization of channels for enabled channels were loaded for the first time. Channels that were initially disabled, but then enabled later, would have the initial default ramps or control points remapped to incorrect values.
This change fixes the issue by changing `initialLoadRef` to be a boolean array, and the loaded status of each channel is tracked individually. This way, the normal initialization can occur even when a channel is loaded later.
From testing it seems like the bug was introduced in #338, but I can't tell exactly what changes to the viewer would have broken this behavior. 
*Estimated review …
> fix: Track channel load status individually

- package-lock.json
- package.json
Picks up the fix for https://github.com/allen-cell-animated/cell-feature-explorer/issues/223 ("volumes are blown out on load") by upgrading to volume-viewer 3.12.3.
1. Open branch and run locally.
2. Open this volume, which was previously bugged: https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails/AICS-14/AICS-14_7889_atlas.json
> refactor: Bump volume-viewer to 3.12.3

- README.md
- package-lock.json
- package.json
- src/aics-image-viewer/components/App/ChannelUpdater.tsx
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
- src/aics-image-viewer/components/AxisClipSliders/index.tsx
- src/aics-image-viewer/components/CellViewerCanvasWrapper/index.tsx
- src/aics-image-viewer/components/ChannelsWidget.tsx
- src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
- src/aics-image-viewer/components/ErrorAlert/index.tsx
- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/components/ViewerStateProvider/types.ts
- src/aics-image-viewer/shared/constants.ts
- src/aics-image-viewer/shared/utils/controlPointsToLut.ts
- src/aics-image-viewer/shared/utils/viewerChannelSettings.ts
- src/index.ts
- webpack.common.js
- website/components/AppWrapper.tsx
- website/components/Modals/ShareModal.tsx
- website/utils/test/datatype_utils.test.ts
- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Problem
=======
Part 1 of 2 for #355, "Rename package + import new VV package." This change performs the rename of the `web-3d-viewer` package to `vole-app` and updates imports to bring in the rename of the `volume-viewer` to `vole-core`.
Part 2 will require a rename of both this and the `volume-viewer` repositories! I'll be updating the GH pages actions and documentation links.
*Estimated review size: small, 10-15 minutes* (some imports got re-sorted so this may appear a bit larger)
Solution
========
- Renamed package in `package.json` and `package-lock.json`.
- Replaced `@aics/volume-viewer` with `@aics/vole-core`.
- Updated README.md
- Updated imports (+ import sorting) in files
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
> refactor: Rename package to `vole-app`

- .github/workflows/nightly.yml
Problem
=======
Fixes #364, "GitHub Pages Nightly build is failing".
Bumps actions/cache to `v4.2.2` from a deprecated version.
*Estimated review size: tiny, <2 minutes*
> fix: Bumped actions/cache to `v4.2.2`

- src/aics-image-viewer/components/ControlPanel/index.tsx
- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/components/TfEditor/styles.css
Review time: tiny <5min
Two minor, easy usability wins:
- Currently, when the control panel is collapsed, the buttons to change the panel to a different tab appear to do nothing:
- Currently, in the "basic mode" transfer function editor, only the purple slider handles poking off the top and bottom of the plot are interactable; the purple lines are not:
- Now, clicking a tab while the control panel is collapsed also un-collapses the control panel
- The lines on the transfer function editor sliders are dashed and quite slim, so rather than make them clickable there's now a second invisible line on top of them with a heavier, solid stroke. Clicking on it has the same behavior as the current slider handles.
- Per @lynwilhelm's feedback, both the slider handles and the lines have a different …
> Usability: open control panel on tab change; make tf editor sliders more draggable

- public/LocalStorageReceiver.tsx
- public/index.tsx
- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/App/types.ts
- src/aics-image-viewer/components/MetadataViewer/index.tsx
- src/aics-image-viewer/shared/types.ts
- website/utils/url_utils.ts
Review time: small-medium
Scientists want to be able to open a selection of files in BioFile Finder as a multi-scene collection in Vol-E. Currently, collections of scenes to open are encoded as a delimited list of URLs in a query parameter in the app URL. This presents a couple problems for the BFF use case:
- Since users can select an arbitrary number of images in BFF, they could very easily create unworkably long Vol-E URLs.
- We want to bring metadata for each scene along from BFF as well. We don't currently have a way to parse metadata out of a query parameter, and even if we did, this could create unworkably long URLs from even a single scene!
For this use case, we've decided to put scene URLs and metadata in Vol-E's *local storage* instead. This presents a new wrinkle: sites can't …
> Store multiscene collections in local storage

- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/components/TfEditor/styles.css
Review size: medium
Closes #373: scientists want channel histograms in the transfer function editor to be displayed in a consistent, configurable range. The current behavior, where the ends of the plot are fixed to the min and max of the data per-frame, is unacceptable.
- Add new UI elements which afford a minimal amount of control over the range of the plot. These controls may later be upgraded with designs that incorporate feedback from this first iteration, but this first iteration should at least be sufficient to meet scientists' needs.
- Now that the range of the plot can be changed, the potential for elements in the plot to render outside the bounds of the plot is much higher. A lot of the code changes here are about ensuring those elements (histogram bars, control points, the line …
> Adjustable range in transfer function editor

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/components/ViewerStateProvider/types.ts
- src/aics-image-viewer/shared/constants.ts
- src/aics-image-viewer/shared/utils/viewerState.ts
- website/utils/test/url_utils.test.ts
Review time: small (~5-15min)
#370 added the ability to modify the range of the transfer function editor's plot. That initial implementation put the state which determines the plot range in the `TfEditor` component itself. This has a significant drawback: that state is destroyed whenever the `TfEditor` component unmounts, including when the channel is disabled, the channel's settings are collapsed, or the user navigates to another tab in the control panel.
Lift the relevant state up into the `ChannelState` type, which is held by `ViewerStateProvider` and persists as long as the `App` component is mounted.
This is a little bit of a strange place to put this information, since that type is otherwise reserved for settings which change the appearance of the channel in the viewport. But (I …
> Persistent transfer function editor range

- src/aics-image-viewer/components/ErrorAlert/styles.css
- src/aics-image-viewer/components/StyleProvider/index.tsx
Review time: xsmall
Two minor styling fixes:
Resolves #257: makes link hover color in warning banner a bit less intense
Resolves #343: restores correct styling in indeterminate checkboxes
> Styling fixes: warning banner, indeterminate checkboxes

- src/aics-image-viewer/components/AxisClipSliders/index.tsx
Review time: xsmall (~5min)
Resolves #371: sliders in the clipping panel with just one handle (slice in 2d modes, time, and/or scene) are 0-indexed. This is confusing.
Keep the underlying state 0-indexed, but modify the component that handles the sliders and spinboxes to display it as 1-indexed. This keeps the code changes relatively limited, but adds some odd complexity in the specific component, since that component also has to handle the case where the slider sets a range between _two_ values.
1. Open the PR preview link
2. Mess with the sliders and spinboxes in the "Clipping" panel (especially in XY mode)
3. Verify everything works as expected
> 1-index clipping panel sliders

- src/aics-image-viewer/components/Toolbar/index.tsx
Closes #390, "reset button does not look like a reset action."
Replaces the reload button icon!
> refactor: Used reload icon instead of undo icon

- src/aics-image-viewer/components/App/index.tsx
- src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
- src/aics-image-viewer/components/ChannelsWidgetRow/styles.css
- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/components/TfEditor/styles.css
- src/aics-image-viewer/components/ViewerStateProvider/types.ts
- src/aics-image-viewer/shared/constants.ts
- src/aics-image-viewer/shared/utils/viewerState.ts
- website/utils/test/url_utils.test.ts
Review time: small (~5-15min)
Resolves #395: implements @lynwilhelm's design for better transfer function editor range controls from #374.
In the first version of range controls (implemented in #370) the user can either "lock to data range" or freely adjust only the maximum of the plot's domain. In this version, users always have full control over both the min and max, and we're never "locked" to any range. Instead, the user can use new push buttons "Fit to data" and "Full range" to apply the default ranges from the previous "locked" and "unlocked" states once.
Also, buttons are more compact, and the language of a preset transfer function button is changed a bit.
| Before | After |
| ------- | ------- |
| ![image](https://github.com/user-attachments/assets/4cb3cdd8-e0e6-4bac-b359-f8c7765b4 …
> Transfer function range editing v2

- package-lock.json
- package.json
This is a patch version upgrade (from 3.15.2). I need this to pick up import resolution fixes in vole-core; my branch upgrading CFE to the latest version doesn't build without it.
> Update vole-core to 3.15.7

- README.md
- documentation/URL_SPEC.md
- package-lock.json
- package.json
- src/aics-image-viewer/components/TfEditor/index.tsx
- src/aics-image-viewer/shared/utils/controlPointsToLut.ts
- src/aics-image-viewer/shared/utils/viewerChannelSettings.ts
- website/utils/test/url_utils.test.ts
- website/utils/url_utils.ts
Problem
=======
Closes #407, "Include direct data values for ramp/control points in URL".
*Estimated review size: small, 5-10 minutes*
Solution
========
- Adds a new format for accepting raw data values as `v{n}` in the `lut` URL argument.
- Updates vole-core to access the new histogram API (`Histogram.getFractionalBinOfValue()`)
- Use `Histogram.getValueFromBinIndex()` in TfEditor calculations
- Updated documentation. 
New feature (non-breaking change which adds functionality)
Steps to Verify:
----------------
1. Open preview link: https://allen-cell-animated.github.io/vole-app/pr-preview/pr-408/?url=https://allencell.s3.amazonaws.com/aics/nuc-morph-dataset/hipsc_fov_nuclei_timelapse_dataset/hipsc_fov_nuclei_timelapse_data_used_for_analysis/baseline_colonies_fov_timelapse_dataset/20200323 …
> feat: Raw data values in URL

- src/aics-image-viewer/components/ViewerStateProvider/ResetStateProvider.ts
Problem
=======
Advances #423 
Solution
========
The settings reset button was grabbing the global default min/max that is data type agnostic (always 0, 255).
This change makes the reset use the current value, i.e. no change when reset settings is clicked.
* Bug fix (non-breaking change which fixes an issue)
> transfer function range reset bug
